@baseUrl = http://localhost:3333/

# @name create_account
POST {{baseUrl}}accounts/deliveryman
Content-Type: application/json

{
  "name": "Rafael",
  "email": "rafael.test@test.com",
  "password": "123456",
  "document": "12345678900"
}